name: Tests and Codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.7
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Prepare
        run: mkdir -p coverage
      - name: Run tests
        run: bun test 2>&1 | sed -e 's/\x1B\[(([0-9]+)(;[0-9]+)*)?[mKHfJ,]//g' -e '1,2d' -E -e 's/\(.+\) .+ \[.+\]$//' -e 's/^.+.test.[mc]?[tj]sx?:$//' -e 's/^ +[0-9]+ (pass|fail|expect\(\) calls)//' -e 's/^ran [0-9]+ tests? across [0-9]+ files?\. +\[.+\]$//i' > coverage/codecov.txt
        env:
          NO_COLOR: 1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
